#!bin/bash
rm -rfv ./.cache
rm -rfv ./.mozilla
rm -rfv /var/cache/*
rm -rfv /etc/firewalld/
rm -rfv /etc/services
rm -rfv /etc/udev
rm -rfv /home/test/.cache/*
rm -rfv /home/test/.local/
rm -rfv /home/test/rpmbuild/sources
rm -rfv /home/rpmbuild/sources
rm -rfv /lib/modules
rm -rfv /lib64/bluetooth
rm -rfv /lib64/dri/i965_dri.so
rm -rfv /lib64/dri/nouveau_dri.so
rm -rfv /lib64/dri/r600_dri.so
rm -rfv /lib64/dri/radeonsi_dri.so
rm -rfv /lib64/dri/virtio_gpu_dri.so
rm -rfv /lib64/dri/vmwgfx_dri.so
rm -rfv /lib64/games
rm -rfv /root/.cache
rm -rfv /root/.mozilla
rm -rfv /root/Downloads
rm -rfv /root/mozilla
rm -rfv /root/rpmbuild/SOURCES
rm -rfv /run/log/journal
rm -rfv /run/udev
rm -rfv /usr/bin/aspell
rm -rfv /usr/bin/brotli
rm -rfv /usr/bin/gawk
