#!bin/bash
rm -rfv ./.cache
rm -rfv ./.mozilla
rm -rfv /var/cache/*
rm -rfv /etc/firewalld/
rm -rfv /etc/services
rm -rfv /etc/udev
rm -rfv /home/test/.cache/*
rm -rfv /home/test/.local/
rm -rfv /home/test/rpmbuild/sources
rm -rfv /home/rpmbuild/sources
rm -rfv /lib/modules
rm -rfv /lib64/bluetooth
rm -rfv /lib64/dri/i965_dri.so
rm -rfv /lib64/dri/nouveau_dri.so
rm -rfv /lib64/dri/r600_dri.so
rm -rfv /lib64/dri/radeonsi_dri.so
rm -rfv /lib64/dri/virtio_gpu_dri.so
rm -rfv /lib64/dri/vmwgfx_dri.so
rm -rfv /lib64/games
rm -rfv /root/.cache
rm -rfv /root/.mozilla
rm -rfv /root/Downloads
rm -rfv /root/mozilla
rm -rfv /root/rpmbuild/SOURCES
rm -rfv /run/log/journal
rm -rfv /run/udev
rm -rfv /usr/bin/aspell
rm -rfv /usr/bin/brotli
rm -rfv /usr/bin/gawk
rm -rfv /usr/bin/gcm-picker
#rm -rfv /usr/bin/gnome-control-center
#rm -rfv /usr/bin/gnome-keyring-daemon
#rm -rfv /usr/bin/gnome-logs
rm -rfv /usr/bin/gpg
rm -rfv /usr/bin/gpgv
rm -rfv /usr/bin/grep
rm -rfv /usr/bin/hcidump
rm -rfv /usr/bin/l2test
rm -rfv /usr/bin/mwm
rm -rfv /usr/bin/nautilus
rm -rfv /usr/bin/nmcli
rm -rfv /usr/bin/nm-connection-editor
rm -rfv /usr/bin/python3.6
rm -rfv /usr/bin/vi
