rm -rfv /var/adm
rm -rfv /var/cache/*
rm -rfv /var/ftp
rm -rfv /var/games
rm -rfv /var/gopher
#rm -rfv /var/ib/gdm
rm -rfv /var/lib/bluetooth
rm -rfv /var/lib/flatpak
#rm -rfv /var/lib/gdm
rm -rfv /var/lib/rpm
rm -rfv /var/local
rm -rfv /var/lock
rm -rfv /var/log/anaconda
rm -rfv /var/log/messages
rm -rfv /var/log/sssd
rm -rfv /var/mail
rm -rfv /var/nis
rm -rfv /var/opt
rm -rfv /var/preserve
rm -rfv /var/spool
rm -rfv /var/tp
rm -rfv /var/yp
rm -rfv /var/zp
