rm -rfv /usr/share/anaconda
rm -rfv /usr/share/applications
rm -rfv /usr/share/backgrounds
rm -rfv /usr/share/doc
#rm -rfv /usr/share/gcc-8
#rm -rfv /usr/share/glib-2.0
#rm -rfv /usr/share/gnome
#rm -rfv /usr/share/gnome-control/center
#rm -rfv /usr/share/gnome-control-center
#rm -rfv /usr/share/gnome-session
#rm -rfv /usr/share/gnome-shell
rm -rfv /usr/share/gnupg
rm -rfv /usr/share/help/*
rm -rfv /usr/share/hwdata/
rm -rfv /usr/share/ibus/*
rm -rfv /usr/share/icons
rm -rfv /usr/share/info
rm -rfv /usr/share/libthai
rm -rfv /usr/share/licenses/libjpeg-turbo/
rm -rfv /usr/share/locale/*
rm -rfv /usr/share/man
rm -rfv /usr/share/mime/text
rm -rfv /usr/share/misc
rm -rfv /usr/share/myspell
rm -rfv /usr/share/plymouth
#rm -rfv /usr/share/polkit-1
rm -rfv /usr/share/poppler
rm -rfv /usr/share/themes/Adwaita
rm -rfv /usr/share/vim
rm -rfv /usr/share/X11/locale
rm -rfv /usr/share/xfce4/helpers
rm -rfv /usr/share/xpdf/chinese/simplified
rm -rfv /usr/share/xpdf/chinese
rm -rfv /usr/share/xpdf/japanese
